# Generated by Django 3.2.16 on 2024-04-30 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(
                related_name="communities", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
